import type { Metadata } from "next";
import { Roboto } from "next/font/google"; // Import the desired Google Font
import "./globals.css";
import { NextUIProvider } from "@nextui-org/react";
import { GlobalProvider } from "@/contexts/GlobalContext";

// Load the Google Font
const roboto = Roboto({
  subsets: ["latin"], // Specify subsets you want (e.g., "latin", "latin-ext")
  weight: ["100", "300", "400", "700"], // Specify font weights you want to use
  variable: "--font-roboto", // Optional: create a CSS variable for the font
});

export const metadata: Metadata = {
  title: "Rhythm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={roboto.className} lang="en">
      <body>
        <GlobalProvider>
          <NextUIProvider>{children}</NextUIProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
